name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sibionic-watch:$(date +%s)

    - name: Tag Docker image
      run: docker tag sibionic-watch:$(date +%s) waynzh/sibionic-watch:latest
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u waynezh --password-stdin
    
    - name: Push Docker image to Docker Hub
      run: docker push waynezh/sibionic-watch:latest
